version: "3.4"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel debug
    restart: always
    networks:
      - skill-wallet-bot

  bot-mongo:
    container_name: bot-mongo
    image: mongo
    volumes:
      - ./data-dev:/data/db
    ports:
      - "27017:27017"
    networks:
      - skill-wallet-bot

  sw-bot:
    container_name: sw-bot
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6005:6005"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - skill-wallet-bot

networks:
  skill-wallet-bot:
