version: "3.4"

services:
  bot-mongo:
    container_name: bot-mongo
    image: mongo
    volumes:
      - ./data-dev:/data/db
    ports:
      - "27018:27018"
    networks:
      - skill-wallet-bot

  sw-bot:
    container_name: sw-bot
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6005:6005"
    command: /bin/bash -c 'yarn; yarn start;'
    networks:
      - skill-wallet-bot

networks:
  skill-wallet-bot:
